#!/usr/bin/env python3
"""Privacy-safe local developer environment scanner for Roast My Computer.

The script is deterministic and local-only. It emits metadata, counts, paths,
risk categories, and redacted secret indicators. It never prints secret values.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import platform
import re
import stat
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

TEXT_EXTENSIONS = {
    ".env", ".txt", ".md", ".markdown", ".json", ".jsonc", ".yaml", ".yml",
    ".toml", ".ini", ".cfg", ".conf", ".properties", ".xml", ".html", ".css",
    ".js", ".jsx", ".ts", ".tsx", ".py", ".rb", ".go", ".rs", ".java",
    ".kt", ".swift", ".php", ".sh", ".bash", ".zsh", ".fish", ".ps1", ".sql",
    ".dockerfile", ".gitignore", ".npmrc", ".pypirc", ".netrc",
}

SECRET_PATTERNS = [
    ("aws_access_key_id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("github_token", re.compile(r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")),
    ("openai_api_key", re.compile(r"\bsk-[A-Za-z0-9][A-Za-z0-9_-]{20,}\b")),
    ("slack_token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b")),
    ("private_key_marker", re.compile(r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----")),
    ("generic_secret_assignment", re.compile(r"(?i)\b(api[_-]?key|secret|token|password|passwd)\b\s*[:=]\s*['\"]?[^'\"\s#]{12,}")),
]

AI_SLOP_PATTERNS = [
    ("phase_plan_language", re.compile(r"(?i)\bphase\s+[0-9ivx]+\b")),
    ("ai_generated_marker", re.compile(r"(?i)\b(generated by ai|generated with chatgpt|as an ai|coding agent|vibe coding)\b")),
    ("future_plan_language", re.compile(r"(?i)\b(will be implemented|future work|coming soon|todo: implement|placeholder implementation)\b")),
    ("overconfident_docs", re.compile(r"(?i)\b(production[- ]ready|enterprise[- ]grade|comprehensive solution)\b")),
]

SKIP_DIR_NAMES = {
    ".git", ".hg", ".svn", ".idea", ".vscode", "node_modules", "vendor",
    "target", "dist", "build", ".next", ".nuxt", ".turbo", ".cache", "__pycache__",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox", "venv", ".venv", "env", ".envdir",
    "Pods", "DerivedData", ".gradle", ".terraform", ".bundle", "coverage",
}

HEAVY_DIR_NAMES = {
    "node_modules", "vendor", "target", "dist", "build", ".next", ".nuxt", ".turbo",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".tox", "venv", ".venv", "env",
    "Pods", "DerivedData", ".gradle", ".terraform", "coverage",
}

METADATA_ONLY_DIR_NAMES = {".ssh", ".aws", ".azure", ".kube", ".gnupg"}
SENSITIVE_CONFIG_NAMES = {".npmrc", ".pypirc", ".netrc", "credentials", "config"}
SENSITIVE_KEY_NAMES = {"id_rsa", "id_dsa", "id_ecdsa", "id_ed25519", "identity", "private_key.pem", "private.pem"}
SENSITIVE_KEY_SUFFIXES = {".pem", ".key", ".p8", ".p12"}
SENSITIVE_TEXT_KEY_SUFFIXES = {".pem", ".key"}
MAX_REPOS_TO_SCAN = 250
MAX_REPOS_DEFAULT = 80
MAX_ENTRIES_DEFAULT = 200_000
MAX_ENTRIES_PER_DIR_DEFAULT = 2_000
MAX_SECONDS_DEFAULT = 60.0

INSTALLER_EXTENSIONS = {".dmg", ".pkg", ".msi", ".exe", ".deb", ".rpm", ".appimage", ".zip", ".tar", ".gz", ".tgz", ".7z", ".rar"}
MANIFEST_FILES = {"package.json", "go.mod", "Cargo.toml", "pyproject.toml", "requirements.txt", "Gemfile", "pom.xml", "build.gradle", "deno.json", "bun.lockb", "pnpm-lock.yaml", "yarn.lock"}
PLAN_DOC_GLOBS = ["*PLAN*.md", "*PRD*.md", "*TODO*.md", "*ROADMAP*.md", "*IMPLEMENTATION*.md", "*DESIGN*.md"]

@dataclass
class Finding:
    category: str
    severity: str
    title: str
    evidence: dict[str, Any] = field(default_factory=dict)
    paths: list[str] = field(default_factory=list)
    detector: str | None = None
    source: str = "user_config"


@dataclass
class ScanBudget:
    """Hard limits so a scan never runs forever. Counts entries and checks wall-clock."""
    max_entries: int = MAX_ENTRIES_DEFAULT
    max_entries_per_dir: int = MAX_ENTRIES_PER_DIR_DEFAULT
    max_seconds: float = MAX_SECONDS_DEFAULT
    start: float = field(default_factory=time.time)
    entries_seen: int = 0
    dirs_truncated: list[str] = field(default_factory=list)
    exhausted_reason: str | None = None

    @property
    def deadline(self) -> float:
        return self.start + self.max_seconds

    def check(self) -> bool:
        """Return True if scanning should continue, False if a limit was hit."""
        if self.entries_seen >= self.max_entries:
            if self.exhausted_reason is None:
                self.exhausted_reason = "entry_limit"
            return False
        if time.time() > self.deadline:
            if self.exhausted_reason is None:
                self.exhausted_reason = "time_limit"
            return False
        return True

    def tick(self) -> bool:
        """Count one entry, then check limits."""
        self.entries_seen += 1
        return self.check()

    @property
    def truncated(self) -> bool:
        return self.exhausted_reason is not None


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def safe_path(path: Path) -> str:
    try:
        return str(path.expanduser().resolve())
    except Exception:
        return str(path)


def path_hash(path: Path) -> str:
    return hashlib.sha256(str(path).encode("utf-8", errors="ignore")).hexdigest()[:12]


def lstat_mode(path: Path) -> int | None:
    try:
        return path.lstat().st_mode
    except OSError:
        return None


def is_dir_no_follow(path: Path) -> bool:
    mode = lstat_mode(path)
    return bool(mode is not None and stat.S_ISDIR(mode))


def is_file_no_follow(path: Path) -> bool:
    mode = lstat_mode(path)
    return bool(mode is not None and stat.S_ISREG(mode))


def is_under_metadata_only_dir(path: Path) -> bool:
    return any(part in METADATA_ONLY_DIR_NAMES for part in path.parts)


def is_sensitive_config_path(path: Path) -> bool:
    return path.name in SENSITIVE_CONFIG_NAMES and is_under_metadata_only_dir(path)


def is_private_key_like_path(path: Path) -> bool:
    name = path.name.lower()
    suffix = path.suffix.lower()
    if name in SENSITIVE_KEY_NAMES:
        return True
    if suffix in SENSITIVE_KEY_SUFFIXES and any(token in name for token in ("key", "private", "secret", "id_")):
        return True
    return False


SEVERITY_RANK = {"low": 1, "medium": 2, "high": 3, "critical": 4}

_EDITOR_CACHE_DIR_NAMES = {"history", ".backups", "user data", "local history"}
_TEST_DIR_NAMES = {"tests", "__tests__", "test", "fixtures", "__fixtures__", "spec", "specs"}


def _cap_severity(finding: "Finding", cap: str) -> None:
    if SEVERITY_RANK.get(finding.severity, 0) > SEVERITY_RANK[cap]:
        finding.severity = cap


def is_public_key_name(name: str) -> bool:
    lower = name.lower()
    return any(tok in lower for tok in ("public", "pubkey", "publickey"))


def path_is_under_app_bundle(path: Path) -> bool:
    return any(part.endswith(".app") for part in path.parts)


def path_is_editor_cache(path: Path) -> bool:
    """Match editor undo-history / auto-backup directories by path *component*,
    not by substring. A project named ``credit-history-api`` is one component
    and must not be treated as editor history; ``User/History/`` is two
    components and should."""
    return any(part.lower() in _EDITOR_CACHE_DIR_NAMES for part in path.parts)


def path_is_test_fixture(path: Path) -> bool:
    if any(part in _TEST_DIR_NAMES for part in path.parts):
        return True
    name = path.name.lower()
    return bool(re.search(r"(?:^|[._-])test(?:[._-]|$)|_spec\.|\.spec\.|\.test\.", name))


def classify_secret_finding(finding: "Finding", path: Path) -> None:
    """Tag ``source`` and cap severity to suppress known false-positive classes.

    - test fixtures (tests/, __tests__/, fixtures/, *_test.*, *.test.*): cap at medium
    - public-key file names (containing "public"/"pubkey"/"publickey"): cap at low;
      tagged ``app_bundle_public_key`` when the file also lives under a *.app bundle,
      ``public_key`` otherwise. A real private key under a developer's *.app project
      directory is NOT downgraded — only the public-key-name signal triggers the cap.
    - editor undo-history / backup directories (User/History/, .backups/, User Data/,
      Local History/): keep severity but tag source=editor_cache so cleanup copy can
      branch (clear editor history vs rotate committed keys)
    """
    if finding.category != "secret_chaos":
        return
    if path_is_test_fixture(path):
        finding.source = "test_fixture"
        _cap_severity(finding, "medium")
        return
    if is_public_key_name(path.name):
        finding.source = "app_bundle_public_key" if path_is_under_app_bundle(path) else "public_key"
        _cap_severity(finding, "low")
        return
    if path_is_editor_cache(path):
        finding.source = "editor_cache"
        return
    finding.source = "user_config"


def is_text_candidate(path: Path, include_sensitive_key_files: bool = False) -> bool:
    name = path.name.lower()
    suffix = path.suffix.lower()
    if name in {".env", ".npmrc", ".pypirc", ".netrc", ".gitconfig", "config", "credentials"}:
        return True
    if include_sensitive_key_files and (name in SENSITIVE_KEY_NAMES or suffix in SENSITIVE_TEXT_KEY_SUFFIXES):
        return True
    if suffix in TEXT_EXTENSIONS:
        return True
    if name in {"dockerfile", "makefile", "justfile", "readme", "license"}:
        return True
    return False


def human_platform() -> str:
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    if system == "windows":
        return "windows"
    if system == "linux":
        return "linux"
    return system or "unknown"


def existing(paths: Iterable[Path]) -> list[Path]:
    out: list[Path] = []
    seen: set[str] = set()
    for p in paths:
        try:
            rp = p.expanduser().resolve()
        except Exception:
            rp = p.expanduser()
        key = str(rp).lower() if os.name == "nt" else str(rp)
        if key in seen:
            continue
        if rp.exists():
            # Skip empty directories — they contribute 0/0 and only clutter scan_roots.
            # Keep roots we cannot list (permission errors) so the scan can record them.
            if is_dir_no_follow(rp):
                try:
                    empty = next(rp.iterdir(), None) is None
                except (OSError, PermissionError):
                    empty = False
                if empty:
                    continue
            seen.add(key)
            out.append(rp)
    return out


def default_roots(include_cache_dirs: bool = False) -> list[Path]:
    home = Path.home()
    roots = [
        home / "Downloads", home / "Desktop", home / "Documents",
        home / "dev", home / "Dev", home / "code", home / "Code", home / "projects", home / "Projects",
        home / "src", home / "repos", home / "workspace", home / "work", home / "Work",
        home / ".config", home / ".ssh", home / ".aws", home / ".azure", home / ".kube", home / ".docker",
    ]
    system = human_platform()
    if system == "macos":
        roots += [home / "Library" / "Application Support", home / "Library" / "Caches"]
    elif system == "linux":
        roots += [home / ".local" / "share", home / ".cache", Path("/opt")]
    elif system == "windows":
        appdata = os.environ.get("APPDATA")
        localappdata = os.environ.get("LOCALAPPDATA")
        userprofile = Path(os.environ.get("USERPROFILE", str(home)))
        roots += [
            userprofile / "source", userprofile / "OneDrive" / "Desktop", userprofile / "OneDrive" / "Documents",
            Path(appdata) if appdata else home / "AppData" / "Roaming",
            Path(localappdata) if localappdata else home / "AppData" / "Local",
            Path(os.environ.get("ProgramFiles", "C:/Program Files")),
            Path(os.environ.get("ProgramFiles(x86)", "C:/Program Files (x86)")),
        ]
    if not include_cache_dirs:
        roots = [p for p in roots if p.name.lower() not in {"caches", ".cache"}]
    return existing(roots)


def file_mtime_age_days(path: Path) -> float | None:
    try:
        return max(0.0, (time.time() - path.stat().st_mtime) / 86400)
    except OSError:
        return None


def run_git(repo: Path, args: list[str], timeout: int = 4) -> str | None:
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), *args],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=timeout,
            check=False,
        )
    except Exception:
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def iter_files(root: Path, max_depth: int, include_cache_dirs: bool, budget: ScanBudget | None = None) -> Iterable[Path]:
    root = root.resolve()
    stack: list[tuple[Path, int]] = [(root, 0)]
    while stack:
        if budget is not None and not budget.check():
            return
        current, depth = stack.pop()
        if depth > max_depth:
            continue
        try:
            entries: list[Path] = []
            listed = 0
            for entry in current.iterdir():
                listed += 1
                if budget is not None and listed > budget.max_entries_per_dir:
                    budget.dirs_truncated.append(safe_path(current))
                    break
                entries.append(entry)
        except (OSError, PermissionError):
            continue
        for entry in entries:
            if budget is not None:
                if not budget.tick():
                    return
            yield entry
            if is_dir_no_follow(entry):
                if entry.name in HEAVY_DIR_NAMES and not include_cache_dirs:
                    continue
                if entry.name in SKIP_DIR_NAMES and entry.name not in HEAVY_DIR_NAMES:
                    continue
                stack.append((entry, depth + 1))


def dir_size_shallow(path: Path, max_entries: int = 2500) -> tuple[int, int]:
    total = 0
    count = 0
    stack = [path]
    while stack and count < max_entries:
        current = stack.pop()
        try:
            for entry in current.iterdir():
                count += 1
                if count >= max_entries:
                    break
                try:
                    if is_dir_no_follow(entry):
                        stack.append(entry)
                    elif is_file_no_follow(entry):
                        total += entry.stat().st_size
                except OSError:
                    continue
        except (OSError, PermissionError):
            continue
    return total, count


def scan_file_for_patterns(path: Path, max_file_size: int, include_sensitive_key_files: bool = False) -> tuple[list[Finding], dict[str, int], list[dict[str, Any]]]:
    findings: list[Finding] = []
    ai_counts: dict[str, int] = {}
    ai_samples: list[dict[str, Any]] = []
    try:
        st = path.stat()
    except OSError:
        return findings, ai_counts, ai_samples
    if st.st_size > max_file_size or not is_text_candidate(path, include_sensitive_key_files=include_sensitive_key_files):
        return findings, ai_counts, ai_samples
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return findings, ai_counts, ai_samples
    for detector, rx in SECRET_PATTERNS:
        matches = list(rx.finditer(text))
        if matches:
            f = Finding(
                category="secret_chaos",
                severity="critical" if detector in {"private_key_marker", "aws_access_key_id", "github_token", "openai_api_key"} else "high",
                title=f"redacted secret-like pattern detected: {detector}",
                detector=detector,
                paths=[safe_path(path)],
                evidence={"matches": len(matches), "redacted": True, "path_hash": path_hash(path)},
            )
            classify_secret_finding(f, path)
            findings.append(f)
    file_samples: dict[str, str] = {}
    for detector, rx in AI_SLOP_PATTERNS:
        matches = list(rx.finditer(text))
        if matches:
            ai_counts[detector] = ai_counts.get(detector, 0) + len(matches)
            file_samples[detector] = matches[0].group(0)[:100]
    for detector, count in sorted(ai_counts.items(), key=lambda kv: kv[1], reverse=True)[:3]:
        ai_samples.append({"detector": detector, "sample": file_samples[detector], "path": safe_path(path), "count": count})
    return findings, ai_counts, ai_samples




def scan_repo(repo: Path, max_file_size: int, content_scan: bool, sensitive_content_scan: bool, budget: ScanBudget | None = None) -> dict[str, Any]:
    repo_info: dict[str, Any] = {
        "path": safe_path(repo),
        "name": repo.name,
        "has_readme": any((repo / name).exists() for name in ["README.md", "README", "readme.md"]),
        "has_gitignore": (repo / ".gitignore").exists(),
        "has_tests": False,
        "manifest_files": [],
        "plan_docs": [],
        "todo_count": 0,
        "ai_slop_markers": {},
        "secret_findings": [],
    }
    for name in MANIFEST_FILES:
        if (repo / name).exists():
            repo_info["manifest_files"].append(name)
    for pattern in PLAN_DOC_GLOBS:
        for match in repo.glob(pattern):
            if match.is_file():
                repo_info["plan_docs"].append(match.name)
    for test_dir in ["test", "tests", "__tests__", "spec", "specs"]:
        if (repo / test_dir).exists():
            repo_info["has_tests"] = True
    status = run_git(repo, ["status", "--porcelain"])
    repo_info["dirty_files"] = len(status.splitlines()) if status else 0
    commit_count = run_git(repo, ["rev-list", "--count", "HEAD"])
    repo_info["commit_count"] = int(commit_count) if commit_count and commit_count.isdigit() else 0
    last_ts = run_git(repo, ["log", "-1", "--format=%ct"])
    if last_ts and last_ts.isdigit():
        repo_info["last_commit_age_days"] = round((time.time() - int(last_ts)) / 86400, 1)
    else:
        repo_info["last_commit_age_days"] = None
    last_subject = run_git(repo, ["log", "-1", "--format=%s"])
    repo_info["last_commit_message_shape"] = classify_commit_message(last_subject or "")
    branches = run_git(repo, ["branch", "--format=%(refname:short)"])
    repo_info["branch_count"] = len(branches.splitlines()) if branches else 0
    remotes = run_git(repo, ["remote"])
    repo_info["remote_count"] = len(remotes.splitlines()) if remotes else 0
    tracked_env = run_git(repo, ["ls-files", ".env", "*.env", ".npmrc", ".pypirc", ".netrc", "*.pem", "*.key", "id_rsa", "id_ed25519"])
    repo_info["tracked_sensitive_config_files"] = tracked_env.splitlines() if tracked_env else []
    tracked_sensitive = set(repo_info["tracked_sensitive_config_files"])

    if content_scan:
        scanned = 0
        for path in iter_files(repo, max_depth=4, include_cache_dirs=False, budget=budget):
            if scanned >= 500:
                break
            if budget is not None and not budget.check():
                break
            if not is_file_no_follow(path):
                continue
            if is_under_metadata_only_dir(path) and not sensitive_content_scan:
                continue
            scanned += 1
            try:
                if path.stat().st_size > max_file_size:
                    continue
                if is_text_candidate(path, include_sensitive_key_files=sensitive_content_scan):
                    text = path.read_text(encoding="utf-8", errors="ignore")
                    repo_info["todo_count"] += len(re.findall(r"(?i)\b(todo|fixme|hack|xxx)\b", text))
                    for detector, rx in AI_SLOP_PATTERNS:
                        count = len(rx.findall(text))
                        if count:
                            markers = repo_info["ai_slop_markers"]
                            markers[detector] = markers.get(detector, 0) + count
                    for secret in scan_file_for_patterns(path, max_file_size, include_sensitive_key_files=sensitive_content_scan)[0]:
                        try:
                            rel = str(path.resolve().relative_to(repo.resolve()))
                        except (ValueError, OSError):
                            rel = ""
                        repo_info["secret_findings"].append({
                            "severity": secret.severity,
                            "detector": secret.detector,
                            "path": secret.paths[0],
                            "redacted": True,
                            "source": secret.source,
                            "tracked_in_git": rel in tracked_sensitive,
                        })
            except Exception:
                continue
    return repo_info


def classify_commit_message(msg: str) -> str:
    normalized = msg.strip().lower()
    if not normalized:
        return "missing"
    if normalized in {"fix", "update", "changes", "wip", "asdf", "test", "init", "initial commit"}:
        return "low_signal"
    if len(normalized) < 8:
        return "too_short"
    return "descriptive"


def score_from_findings(summary: dict[str, Any]) -> dict[str, Any]:
    repos = summary["repositories"]
    totals = summary["totals"]
    secret_count = totals["secret_risk_count"]
    abandoned = [r for r in repos if (r.get("last_commit_age_days") or 9999) > 180 or r.get("commit_count", 0) <= 1]
    dirty = [r for r in repos if r.get("dirty_files", 0) > 0]
    no_readme = [r for r in repos if not r.get("has_readme")]
    ai_marked = [r for r in repos if sum(r.get("ai_slop_markers", {}).values()) + len(r.get("plan_docs", [])) > 2]
    heavy_dirs = totals["heavy_dependency_dirs"]
    installers = totals["installer_archive_count"]
    downloads = totals["download_file_count"]
    tool_markers = totals["tool_marker_count"]

    def clamp(n: float) -> int:
        return int(max(0, min(100, round(n))))

    scores = {
        "digital_landfill": clamp(min(100, installers * 4 + downloads * 0.4 + heavy_dirs * 5 + totals["large_file_count"] * 3)),
        "abandoned_projects": clamp((len(abandoned) / max(len(repos), 1)) * 100 + max(0, len(repos) - 10) * 2),
        "secret_chaos": clamp(secret_count * 18 + totals["tracked_sensitive_config_count"] * 20),
        "git_shame": clamp((len(dirty) / max(len(repos), 1)) * 40 + (len(no_readme) / max(len(repos), 1)) * 25 + totals["low_signal_commit_count"] * 3),
        "ai_slop": clamp((len(ai_marked) / max(len(repos), 1)) * 55 + totals["ai_marker_count"] * 2 + totals["plan_doc_count"] * 3),
        "tool_hoarder": clamp(tool_markers * 5 + heavy_dirs * 4),
    }
    overall = clamp(sum(scores.values()) / len(scores))
    title = title_for(scores, overall)
    return {"overall": overall, "dimensions": scores, "title": title}


def title_for(scores: dict[str, int], overall: int) -> str:
    top = max(scores.items(), key=lambda kv: kv[1])[0]
    if overall >= 85:
        prefix = "Digital Disaster Artist"
    elif overall >= 65:
        prefix = "Localhost Menace"
    elif overall >= 40:
        prefix = "Mildly Cursed Developer"
    else:
        prefix = "Suspiciously Functional Adult"
    suffixes = {
        "digital_landfill": "Archive Hoarder",
        "abandoned_projects": "Half-Finished Project Goblin",
        "secret_chaos": "Plaintext Token Philanthropist",
        "git_shame": "Commit Avoidance Specialist",
        "ai_slop": "Vibe Coding Spill Response",
        "tool_hoarder": "Toolchain Collector",
    }
    return f"{prefix} · {suffixes.get(top, 'Computer Roast Subject')}"


def workspace_root() -> Path:
    try:
        return Path.cwd().resolve()
    except Exception:
        return Path.cwd()


def normalize_scope(raw: str) -> str:
    """Return the canonical scan scope.

    Public scopes are intentionally only:
    - project: current working directory, plus explicitly supplied paths
    - global: platform defaults plus memory/context roots and explicitly supplied paths

    Older aliases remain accepted so existing commands do not break, but new docs
    should present only Project and Global.
    """
    value = (raw or "project").strip().lower()
    aliases = {
        "project": "project",
        "workspace": "project",
        "repo": "project",
        "local": "project",
        "global": "global",
        "agent-decided": "global",
        "agent_decided": "global",
        "full": "global",
        "computer": "global",
        "custom": "custom",
    }
    if value not in aliases:
        raise ValueError(f"unknown scope: {raw!r}; use 'project' or 'global'")
    return aliases[value]


def build_scan_roots(args: argparse.Namespace) -> tuple[list[Path], str, list[Path]]:
    """Build roots from the canonical Project/Global scope.

    project: scan the current working directory. Explicit paths are
    allowed and are treated as user-approved additions.

    global: scan common platform roots plus memory/context roots and explicit
    paths. This is the most accurate mode and may require filesystem permission
    approval in sandboxed environments.
    """
    provided = [Path(p).expanduser() for p in [*args.paths, *args.root, *args.memory_root]]
    provided_roots = existing(provided)

    if args.no_default_roots:
        scope = "custom"
    else:
        scope = normalize_scope(args.scope)

    if scope == "project":
        roots = existing([workspace_root(), *provided_roots])
    elif scope == "custom":
        roots = provided_roots
    else:
        roots = [*default_roots(include_cache_dirs=args.include_cache_dirs), *provided_roots]
        roots = existing(roots)

    if not roots:
        roots = [workspace_root() if scope == "project" else Path.home()]

    return roots, scope, provided_roots

def summarize_roots(roots: list[Path], max_depth: int, content_scan: bool, max_file_size: int, include_cache_dirs: bool, sensitive_content_scan: bool, budget: ScanBudget | None = None) -> tuple[dict[str, Any], list[Path]]:
    findings: list[Finding] = []
    totals = {
        "files_seen": 0,
        "dirs_seen": 0,
        "download_file_count": 0,
        "installer_archive_count": 0,
        "large_file_count": 0,
        "heavy_dependency_dirs": 0,
        "tool_marker_count": 0,
        "secret_risk_count": 0,
        "tracked_sensitive_config_count": 0,
        "ai_marker_count": 0,
        "plan_doc_count": 0,
        "low_signal_commit_count": 0,
    }
    root_summaries: list[dict[str, Any]] = []
    heavy_examples: list[str] = []
    installer_examples: list[str] = []
    large_examples: list[str] = []
    tool_markers: list[str] = []
    ai_counts: dict[str, int] = {}
    ai_samples: list[dict[str, Any]] = []
    repos: list[Path] = []
    seen_repos: set[str] = set()

    for root in roots:
        if budget is not None and not budget.check():
            break
        root_info = {"path": safe_path(root), "files": 0, "dirs": 0, "bytes_shallow": 0, "permission_errors": 0, "installer_archive_count": 0}
        if is_dir_no_follow(root) and (root / ".git").exists():
            key = safe_path(root)
            if key not in seen_repos:
                seen_repos.add(key)
                repos.append(root)
        if is_file_no_follow(root):
            entries = [root]
        else:
            entries = iter_files(root, max_depth=max_depth, include_cache_dirs=include_cache_dirs, budget=budget)
        for entry in entries:
            try:
                if is_dir_no_follow(entry):
                    totals["dirs_seen"] += 1
                    root_info["dirs"] += 1
                    if (entry / ".git").exists():
                        key = safe_path(entry)
                        if key not in seen_repos:
                            seen_repos.add(key)
                            repos.append(entry)
                    if entry.name in HEAVY_DIR_NAMES:
                        totals["heavy_dependency_dirs"] += 1
                        if len(heavy_examples) < 12:
                            size, count = dir_size_shallow(entry, 1200)
                            heavy_examples.append(f"{safe_path(entry)} ({round(size / (1024 * 1024), 1)} MB sampled, {count} entries sampled)")
                    if entry.name in {".nvm", ".pyenv", ".asdf", ".mise", ".rustup", ".cargo", ".bun", ".deno", ".npm", ".pnpm-store", ".docker", ".kube", "scoop", "Chocolatey"}:
                        totals["tool_marker_count"] += 1
                        if len(tool_markers) < 15:
                            tool_markers.append(safe_path(entry))
                    continue
                if not is_file_no_follow(entry):
                    continue
                totals["files_seen"] += 1
                root_info["files"] += 1
                st = entry.stat()
                root_info["bytes_shallow"] += st.st_size
                suffix = entry.suffix.lower()
                if "download" in root.name.lower() or "downloads" in str(root).lower():
                    totals["download_file_count"] += 1
                if suffix in INSTALLER_EXTENSIONS:
                    totals["installer_archive_count"] += 1
                    root_info["installer_archive_count"] += 1
                    if len(installer_examples) < 12:
                        installer_examples.append(safe_path(entry))
                if st.st_size > 500 * 1024 * 1024:
                    totals["large_file_count"] += 1
                    if len(large_examples) < 12:
                        large_examples.append(f"{safe_path(entry)} ({round(st.st_size / (1024 ** 3), 2)} GB)")
                if is_sensitive_config_path(entry):
                    cfg_f = Finding(
                        category="secret_chaos",
                        severity="medium",
                        title="sensitive configuration file present",
                        paths=[safe_path(entry)],
                        evidence={"metadata_only": True, "content_scan_skipped": bool(not sensitive_content_scan), "path_hash": path_hash(entry)},
                    )
                    classify_secret_finding(cfg_f, entry)
                    findings.append(cfg_f)
                if is_private_key_like_path(entry):
                    pk_f = Finding(
                        category="secret_chaos",
                        severity="critical",
                        title="private key-like file present",
                        paths=[safe_path(entry)],
                        evidence={"metadata_only": True, "content_scan_skipped": bool(not sensitive_content_scan), "path_hash": path_hash(entry)},
                        detector="private_key_file",
                    )
                    classify_secret_finding(pk_f, entry)
                    findings.append(pk_f)
                if content_scan and (sensitive_content_scan or not is_under_metadata_only_dir(entry)):
                    secret_findings, local_ai, local_samples = scan_file_for_patterns(entry, max_file_size, include_sensitive_key_files=sensitive_content_scan)
                    findings.extend(secret_findings)
                    for k, v in local_ai.items():
                        ai_counts[k] = ai_counts.get(k, 0) + v
                    ai_samples.extend(local_samples)
            except PermissionError:
                root_info["permission_errors"] += 1
            except OSError:
                continue
        root_summaries.append(root_info)

    for f in findings:
        if f.category == "secret_chaos":
            totals["secret_risk_count"] += 1
    totals["ai_marker_count"] = sum(ai_counts.values())

    # Build bounded, diverse ai_markers examples: top samples by count, capped at 3 per
    # detector so one verbose file can't monopolize the list. Mirrors the other 4 example
    # buckets (heavy_dependency_dirs / installer_archives / large_files / tool_markers).
    ai_marker_examples: list[dict[str, Any]] = []
    per_detector: dict[str, int] = {}
    for s in sorted(ai_samples, key=lambda d: d.get("count", 0), reverse=True):
        det = s["detector"]
        if per_detector.get(det, 0) >= 3:
            continue
        per_detector[det] = per_detector.get(det, 0) + 1
        ai_marker_examples.append(s)
        if len(ai_marker_examples) >= 12:
            break

    return {
        "root_summaries": root_summaries,
        "findings": [f.__dict__ for f in findings],
        "totals": totals,
        "examples": {
            "heavy_dependency_dirs": heavy_examples,
            "installer_archives": installer_examples,
            "large_files": large_examples,
            "tool_markers": tool_markers,
            "ai_markers": ai_marker_examples,
        },
        "ai_marker_counts": ai_counts,
    }, repos


def main() -> int:
    parser = argparse.ArgumentParser(description="Scan a local developer environment for Roast My Computer.")
    parser.add_argument("--output", required=True, help="Path to write scan JSON.")
    parser.add_argument("paths", nargs="*", help="Extra roots to scan. Intuitive shorthand for --root; accepts normal paths like ~/dev.")
    parser.add_argument("--scope", default="project", help="project scans the current working directory; global scans common platform roots plus memory/context roots and may need permission approval.")
    parser.add_argument("--root", action="append", default=[], help="Explicit root to scan. Repeatable.")
    parser.add_argument("--memory-root", action="append", default=[], help="Root inferred from agent memory/context. Repeatable.")
    parser.add_argument("--no-default-roots", action="store_true", default=False, help=argparse.SUPPRESS)
    parser.add_argument("--max-depth", type=int, default=4, help="Directory traversal depth. Default 4 covers most repo layouts; raise to 6 for deep monorepos (slower, capped by --max-entries and --max-seconds).")
    parser.add_argument("--max-file-size", type=int, default=256 * 1024, help="Max bytes for text content scans.")
    parser.add_argument("--max-entries", type=int, default=MAX_ENTRIES_DEFAULT, help="Hard cap on total filesystem entries scanned across all roots. Prevents run-forever on huge trees.")
    parser.add_argument("--max-entries-per-dir", type=int, default=MAX_ENTRIES_PER_DIR_DEFAULT, help="Hard cap on entries listed from a single directory. Protects against one wide dir starving the scan.")
    parser.add_argument("--max-seconds", type=float, default=MAX_SECONDS_DEFAULT, help="Wall-clock budget in seconds. The scan stops and writes partial results when exceeded. The hard guarantee against running forever.")
    parser.add_argument("--max-repos", type=int, default=MAX_REPOS_DEFAULT, help="Max repositories to inspect with git. Capped at %d." % MAX_REPOS_TO_SCAN)
    parser.add_argument("--content-scan", dest="content_scan", action="store_true", default=True)
    parser.add_argument("--no-content-scan", dest="content_scan", action="store_false")
    parser.add_argument("--sensitive-content-scan", dest="sensitive_content_scan", action="store_true", default=True, help=argparse.SUPPRESS)
    parser.add_argument("--metadata-only-sensitive-dirs", dest="sensitive_content_scan", action="store_false", help="Advanced: do not read text content inside .ssh, .aws, .azure, .kube, or .gnupg; record metadata-only findings there.")
    parser.add_argument("--include-cache-dirs", action="store_true", default=False, help="Traverse known heavy/cache dependency dirs such as node_modules and target. Slower; off by default.")
    args = parser.parse_args()

    roots, effective_scope, provided_roots = build_scan_roots(args)
    budget = ScanBudget(max_entries=args.max_entries, max_entries_per_dir=args.max_entries_per_dir, max_seconds=args.max_seconds)
    scan_start = time.time()

    scan, discovered_repos = summarize_roots(roots, args.max_depth, args.content_scan, args.max_file_size, args.include_cache_dirs, args.sensitive_content_scan, budget=budget)
    repos = discovered_repos
    repo_cap = min(args.max_repos, MAX_REPOS_TO_SCAN)
    repo_infos: list[dict[str, Any]] = []
    repo_scan_truncated = False
    for repo in repos[:repo_cap]:
        if not budget.check():
            repo_scan_truncated = True
            break
        repo_infos.append(scan_repo(repo, args.max_file_size, args.content_scan, args.sensitive_content_scan, budget=budget))
    if len(repos) > repo_cap:
        repo_scan_truncated = True
    wall_clock = round(time.time() - scan_start, 2)

    for repo in repo_infos:
        scan["totals"]["tracked_sensitive_config_count"] += len(repo.get("tracked_sensitive_config_files", []))
        scan["totals"]["low_signal_commit_count"] += 1 if repo.get("last_commit_message_shape") == "low_signal" else 0
        scan["totals"]["plan_doc_count"] += len(repo.get("plan_docs", []))
        scan["totals"]["ai_marker_count"] += sum(repo.get("ai_slop_markers", {}).values())
        scan["totals"]["secret_risk_count"] += len(repo.get("secret_findings", []))

    summary = {
        "schema_version": "1.6.0",
        "generated_at": now_iso(),
        "host": {
            "platform": human_platform(),
            "python": platform.python_version(),
            "hostname_hash": hashlib.sha256(platform.node().encode()).hexdigest()[:12] if platform.node() else None,
        },
        "scan_policy": {
            "local_only": True,
            "scope": effective_scope,
            "project_root": safe_path(workspace_root()),
            "content_scan": bool(args.content_scan),
            "sensitive_content_scan": bool(args.sensitive_content_scan),
            "sensitive_dirs_metadata_only": bool(not args.sensitive_content_scan),
            "secrets_redacted": True,
            "max_depth": args.max_depth,
            "max_file_size": args.max_file_size,
            "provided_root_count": len(provided_roots),
            "repository_discovered_count": len(repos),
            "repository_scanned_count": len(repo_infos),
            "repository_scan_truncated": repo_scan_truncated,
            "repository_scan_limit": repo_cap,
            "entry_count": budget.entries_seen,
            "entry_limit": budget.max_entries,
            "entries_truncated": budget.exhausted_reason == "entry_limit",
            "dirs_truncated_count": len(budget.dirs_truncated),
            "wall_clock_seconds": wall_clock,
            "wall_clock_limit_seconds": budget.max_seconds,
            "wall_clock_truncated": budget.exhausted_reason == "time_limit",
            "truncated": budget.truncated,
            "truncation_reason": budget.exhausted_reason,
        },
        "scan_roots": [safe_path(p) for p in roots],
        "root_summaries": scan["root_summaries"],
        "totals": scan["totals"],
        "examples": scan["examples"],
        "findings": scan["findings"],
        "repositories": repo_infos,
    }
    summary["scores"] = score_from_findings(summary)

    out = Path(args.output).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(str(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
