#!/usr/bin/env bash
# Collect signal-only evidence for a Production Go style codebase review.
# Usage: collect_go_production_signals.sh [repo-path]
# Optional env vars: RUN_RACE=1 RUN_BENCH=1 TIMEOUT_SECS=180 MAX_OUTPUT_LINES=160

set -u

ROOT="${1:-.}"
TIMEOUT_SECS="${TIMEOUT_SECS:-180}"
MAX_OUTPUT_LINES="${MAX_OUTPUT_LINES:-160}"
RUN_RACE="${RUN_RACE:-0}"
RUN_BENCH="${RUN_BENCH:-0}"

if [ ! -d "$ROOT" ]; then
  echo "error: path does not exist or is not a directory: $ROOT" >&2
  exit 2
fi

cd "$ROOT" || exit 2
ROOT_ABS="$(pwd)"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

section() {
  printf '\n## %s\n\n' "$1"
}

subsection() {
  printf '\n### %s\n\n' "$1"
}

run_cmd() {
  title="$1"
  cmd="$2"
  subsection "$title"
  printf '```\n$ %s\n' "$cmd"
  out="$tmpdir/cmd.out"
  if command -v timeout >/dev/null 2>&1; then
    timeout "$TIMEOUT_SECS" bash -lc "$cmd" >"$out" 2>&1
  else
    bash -lc "$cmd" >"$out" 2>&1
  fi
  code=$?
  sed -n "1,${MAX_OUTPUT_LINES}p" "$out"
  line_count="$(wc -l < "$out" | tr -d ' ')"
  if [ "$line_count" -gt "$MAX_OUTPUT_LINES" ]; then
    echo "... output truncated after ${MAX_OUTPUT_LINES} lines; full output had ${line_count} lines"
  fi
  printf 'exit code: %s\n```\n\n' "$code"
}

list_matches() {
  title="$1"
  pattern="$2"
  include_glob="${3:-*.go}"
  subsection "$title"
  printf '```\n'
  if find . -type f -name "$include_glob" -not -path './.git/*' -not -path './vendor/*' -print0 | xargs -0 grep -HnE "$pattern" 2>/dev/null | sed -n "1,${MAX_OUTPUT_LINES}p"; then
    true
  else
    true
  fi
  printf '```\n\n'
}

count_files() {
  find . -type f "$@" -not -path './.git/*' -not -path './vendor/*' | wc -l | tr -d ' '
}

printf '# Go production review signal report\n\n'
printf 'repository: `%s`\n\n' "$ROOT_ABS"
printf 'generated by: `scripts/collect_go_production_signals.sh`\n\n'
printf 'note: this is evidence for review, not a final verdict. manually inspect code paths behind each signal.\n\n'

section "Repository inventory"
GO_FILES="$(count_files -name '*.go')"
TEST_FILES="$(count_files -name '*_test.go')"
MOD_FILES="$(count_files -name 'go.mod')"
printf -- '- go files: %s\n' "$GO_FILES"
printf -- '- test files: %s\n' "$TEST_FILES"
printf -- '- go.mod files: %s\n' "$MOD_FILES"
printf -- '- current directory: `%s`\n' "$ROOT_ABS"

subsection "Detected module roots"
printf '```\n'
find . -type f -name 'go.mod' -not -path './vendor/*' -not -path './.git/*' -print | sed 's#/go.mod$##' | sort
printf '```\n\n'

section "Formatting and imports"
run_cmd "go version and environment" "go version && go env GOMOD GOPATH GOOS GOARCH"
run_cmd "gofmt files requiring formatting" "find . -type f -name '*.go' -not -path './vendor/*' -not -path './.git/*' -print0 | xargs -0 -r gofmt -l"
run_cmd "gofmt -s files with simplifications available" "while IFS= read -r -d '' f; do if ! cmp -s <(gofmt -s \"\$f\") \"\$f\"; then printf '%s\n' \"\$f\"; fi; done < <(find . -type f -name '*.go' -not -path './vendor/*' -not -path './.git/*' -print0)"
if command -v goimports >/dev/null 2>&1; then
  run_cmd "goimports files requiring import cleanup" "find . -type f -name '*.go' -not -path './vendor/*' -not -path './.git/*' -print0 | xargs -0 -r goimports -l"
else
  subsection "goimports availability"
  printf 'goimports not found on PATH. review imports with goimports where available.\n\n'
fi

section "Go module and package checks"
if [ "$MOD_FILES" -gt 0 ]; then
  while IFS= read -r mod; do
    dir="$(dirname "$mod")"
    subsection "Module: $dir"
    (cd "$dir" && run_cmd "go list ./..." "go list ./..." && run_cmd "go test ./..." "go test ./... -count=1" && run_cmd "go vet ./..." "go vet ./..." && run_cmd "go test coverage" "go test ./... -cover -count=1")
    if [ "$RUN_RACE" = "1" ]; then
      (cd "$dir" && run_cmd "go test -race ./..." "go test -race ./... -count=1")
    else
      subsection "go test -race ./..."
      printf 'skipped. rerun with RUN_RACE=1 for race detector evidence.\n\n'
    fi
    if [ "$RUN_BENCH" = "1" ]; then
      (cd "$dir" && run_cmd "go test benchmarks" "go test ./... -bench=. -benchmem -run='^$'")
    else
      subsection "go test benchmarks"
      printf 'skipped. rerun with RUN_BENCH=1 for benchmark evidence.\n\n'
    fi
  done < <(find . -type f -name 'go.mod' -not -path './vendor/*' -not -path './.git/*' | sort)
else
  run_cmd "go list ./... without go.mod" "go list ./..."
  run_cmd "go test ./... without go.mod" "go test ./... -count=1"
  run_cmd "go vet ./... without go.mod" "go vet ./..."
fi

section "Optional analyzer output"
if command -v staticcheck >/dev/null 2>&1; then
  run_cmd "staticcheck ./..." "staticcheck ./..."
else
  subsection "staticcheck availability"
  printf 'staticcheck not found on PATH. install or pin it if the project requires it.\n\n'
fi
if command -v golangci-lint >/dev/null 2>&1; then
  run_cmd "golangci-lint run" "golangci-lint run"
else
  subsection "golangci-lint availability"
  printf 'golangci-lint not found on PATH. use project-pinned linters when available.\n\n'
fi
if command -v errcheck >/dev/null 2>&1; then
  run_cmd "errcheck ./..." "errcheck ./..."
else
  subsection "errcheck availability"
  printf 'errcheck not found on PATH. staticcheck/golangci-lint may cover some ignored-error cases.\n\n'
fi

section "Project automation and pinned tools"
subsection "CI, build, and deployment files"
printf '```\n'
find . -maxdepth 4 \( -path './.github/workflows/*' -o -name '.travis.yml' -o -name 'Jenkinsfile' -o -name '.drone.yml' -o -name 'Makefile' -o -name 'Taskfile.yml' -o -name 'Dockerfile' -o -name 'docker-compose.yml' \) -print | sort | sed -n "1,${MAX_OUTPUT_LINES}p"
printf '```\n\n'
list_matches "Pinned Go tools and analyzer references" 'tools|staticcheck|golangci-lint|errcheck|goimports|gofmt|gosec|govet' '*'

section "Documentation and public API signals"
list_matches "Package comments" '^// Package [A-Za-z0-9_]+' '*.go'
list_matches "Exported declarations" '^(type|func|var|const) [A-Z][A-Za-z0-9_]+' '*.go'
list_matches "Example tests" '^func Example' '*_test.go'

section "Testing signals"
list_matches "Test functions" '^func Test' '*_test.go'
list_matches "Table-driven test hints" '\[\]struct|cases :=|tests :=|tt :=' '*_test.go'
list_matches "HTTP handler test hints" 'httptest|ResponseRecorder|NewRequest|ServeHTTP' '*_test.go'
list_matches "Benchmark functions" '^func Benchmark' '*_test.go'
list_matches "Fuzz functions" '^func Fuzz' '*.go'

section "Error-handling and style review signals"
list_matches "Potential capitalized error strings" '(fmt\.Errorf|errors\.New)\("[A-Z]' '*.go'
list_matches "Potential ignored write/close/decode errors" '\.(Write|WriteString|Close|Decode|Encode)\(' '*.go'
list_matches "Potential shadowing-sensitive short declarations" 'if .*:=.*err|err :=' '*.go'
list_matches "Empty interface usage" 'interface\{\}|any' '*.go'

section "String, Unicode, and text-handling signals"
list_matches "Unicode-aware packages" 'unicode\.|norm\.|x/text|strings\.EqualFold|strings\.FieldsFunc|strings\.Map' '*.go'
list_matches "Case-folding patterns to inspect" 'strings\.ToLower\(|strings\.ToUpper\(' '*.go'
list_matches "String concatenation in loops or hot paths to inspect" '\+=|\+ .*string|fmt\.Sprintf|strings\.Builder' '*.go'

section "Concurrency signals"
list_matches "Goroutine launches" '^[[:space:]]*go[[:space:]]' '*.go'
list_matches "Synchronization primitives" 'sync\.WaitGroup|errgroup|sync\.Mutex|sync\.RWMutex|sync\.Map|atomic\.|make\(chan|chan ' '*.go'
list_matches "Sleep used in code" 'time\.Sleep' '*.go'
list_matches "Map declarations and writes to inspect for concurrent access" 'map\[|make\(map|\[[^]]+\][[:space:]]*=' '*.go'

section "Security and web-service signals"
list_matches "CSRF, HSTS, CSP, and secure-header hints" 'csrf|nosurf|Strict-Transport-Security|Content-Security-Policy|secure\.|Header\(\)\.Set|Header\(\)\.Add' '*.go'
list_matches "SQL and query construction hints" 'SELECT|INSERT|UPDATE|DELETE|db\.(Query|Exec|Prepare)|\.Query\(|\.Exec\(|FormValue\(|\+' '*.go'
list_matches "HTTP server and handler hints" 'http\.Handle|ListenAndServe|http\.Server|http\.Client|http\.Get|http\.Post' '*.go'

section "Observability and production-readiness signals"
list_matches "Logging hints" 'log\.|logger|zap\.|zerolog|slog\.' '*.go'
list_matches "Metrics and tracing hints" 'prometheus|metrics|expvar|statsd|opentelemetry|otel|trace|dashboard|alert' '*'

section "Manual review reminders"
cat <<'EOF'
- Verify whether every finding has file-level evidence and a concrete runtime or maintenance impact.
- Review goroutine lifecycles, shared memory, and handler-spawned background work manually.
- Treat grep matches as prompts for review, not automatic failures.
- Prefer project-pinned tool versions when they exist.
- Re-run expensive checks explicitly with RUN_RACE=1 and RUN_BENCH=1 when the codebase and environment permit it.
EOF
